apiVersion: v1
kind: Secret
metadata:
  name: {{ include "dex-k8s-authenticator.fullname" . }}
  labels:
    {{- include "dex-k8s-authenticator.labels" . | nindent 4 }}
  {{- with .Values.secret.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
data:
  config.yaml: {{ set .Values.config "listen" "http://0.0.0.0:80" | toYaml | b64enc | quote }}
