# Default values for telemetrygen.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

nameOverride: ""
fullnameOverride: ""

# https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/cmd/telemetrygen
enabled: true

#otlpEndpoint: ""

replicaCount: 1

image:
  repository: ghcr.io/open-telemetry/opentelemetry-collector-contrib/telemetrygen
  pullPolicy: IfNotPresent
  tag: "v0.108.0"

restartPolicy: Always

traces:
  enabled: true
  duration: 10m
  rate: 1
metrics:
  enabled: true
  duration: 10m
  rate: 1
logs:
  enabled: true
  duration: 10m
  rate: 1
  body: |-
    {"message": "Default log message..."}

podAnnotations: {}
podLabels: {}

imagePullSecrets: []

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

