{{- if .Values.corootClusterAgent.enabled -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "corootClusterAgent.name" . }}
  labels:
    {{- include "corootClusterAgent.labels" . | nindent 4 }}

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "corootClusterAgent.name" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "corootClusterAgent.name" . }}
    namespace: {{ include "coroot.namespace" . }}
roleRef:
  kind: ClusterRole
  name: view
  apiGroup: rbac.authorization.k8s.io

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "corootClusterAgent.name" . }}
  labels:
    {{- include "corootClusterAgent.labels" . | nindent 4 }}
data:
  config.yaml: |
  {{- toYaml .Values.corootClusterAgent.config | nindent 4 }}

---

apiVersion: v1
kind: Service
metadata:
  name: {{ include "corootClusterAgent.name" . }}
  labels:
    {{- include "corootClusterAgent.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    {{- include "corootClusterAgent.selectorLabels" . | nindent 6 }}

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "corootClusterAgent.name" . }}
  labels:
    {{- include "corootClusterAgent.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "corootClusterAgent.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ toYaml .Values.corootClusterAgent.config | sha256sum }}
        {{- with .Values.corootClusterAgent.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "corootClusterAgent.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.corootClusterAgent.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "corootClusterAgent.name" . }}
      securityContext:
        {{- toYaml .Values.corootClusterAgent.podSecurityContext | nindent 8 }}
      containers:
        - name: cluster-agent
          securityContext:
            {{- toYaml .Values.corootClusterAgent.securityContext | nindent 12 }}
          image: "{{ .Values.corootClusterAgent.image.repository }}:{{ .Values.corootClusterAgent.image.tag }}"
          imagePullPolicy: {{ .Values.corootClusterAgent.image.pullPolicy }}
          env:
            - name: CLICKHOUSE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "coroot.clickhouse.fullname" . }}
                  key: admin-password
          {{- with .Values.corootClusterAgent.env }}
          {{- . | toYaml | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.corootClusterAgent.resources | nindent 12 }}
          volumeMounts:
            - name: config
              mountPath: /config.yaml
              subPath: config.yaml
      volumes:
        - name: config
          configMap:
            name: {{ include "corootClusterAgent.name" . }}
      {{- with .Values.corootClusterAgent.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.corootClusterAgent.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.corootClusterAgent.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end -}}
