{{ if .Values.otelcol.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: otelcontribcol
  labels:
    app: otelcontribcol
    {{- include "uptrace.labels" . | nindent 4 }}
data:
  config.yaml: |
    receivers:
      otlp:
        protocols:
          grpc:
          http:
      k8s_cluster:
        auth_type: serviceAccount
        collection_interval: 15s
      kubeletstats:
        collection_interval: 15s
        auth_type: "serviceAccount"
        endpoint: "https://${env:K8S_NODE_NAME}:10250"
        insecure_skip_verify: true
    processors:
      resourcedetection:
        detectors: ['system']
      cumulativetodelta:
      batch:
        send_batch_size: 10000
        timeout: 15s
    exporters:
      debug:
      otlp/local:
        endpoint: http://my-uptrace:14317
        tls: { insecure: true }
        headers: { 'uptrace-dsn': 'http://project1_secret_token@localhost:14317/1' }
    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: [batch]
          exporters: [otlp/local]
        metrics:
          receivers: [otlp, k8s_cluster, kubeletstats]
          processors: [cumulativetodelta, batch]
          exporters: [debug, otlp/local]
        logs:
          receivers: [otlp, k8s_cluster]
          processors: [batch]
          exporters: [debug, otlp/local]
{{ end }}
