{{- if .Values.postgresql.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: uptrace-postgresql-secret
type: Opaque
data:
  POSTGRES_USER: {{ .Values.uptrace.config.pg.user | b64enc | quote }}
  POSTGRES_PASSWORD: {{ .Values.uptrace.config.pg.password | b64enc | quote }}
{{- end }}
