{{ if .Values.postgresql.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: uptrace-postgresql
  labels:
    app: postgresql
    {{- include "uptrace.labels" . | nindent 4 }}
spec:
  type: {{ .Values.postgresql.service.type }}
  ports:
    - port: {{ .Values.postgresql.service.port }}
      targetPort: tcp
      protocol: TCP
      name: tcp
  selector:
    app: postgresql
    {{- include "uptrace.selectorLabels" . | nindent 4 }}
{{ end }}
