apiVersion: v1
kind: Secret
type: kubernetes.io/basic-auth
metadata:
  name: {{ .Release.Name }}
data:
  username: {{ .Values.secret.username | default (randAlphaNum 10) | b64enc | quote }}
  password: {{ .Values.secret.password | default (randAlphaNum 64) | b64enc | quote }}
  database: {{ .Values.secret.password | default (randAlphaNum 64) | b64enc | quote }}

