apiVersion: v1
kind: Secret
metadata:
  name: infisical-secrets
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  AUTH_SECRET: {{ .Values.secret.authSecret }}a886884bf5043a3cc2ab538f3c4ee28f
  ENCRYPTION_KEY: {{ .Values.secret.encryptionKey }}
  REDIS_URL: {{ .Values.secret.redisURI }}
  DB_CONNECTION_URI: {{ .Values.secret.postgresURI }}
