image:
  tag: v1.0.27

autoscaler:
  image:
    repository: keyval/odigos-autoscaler

scheduler:
  image:
    repository: keyval/odigos-scheduler

instrumentor:
  deleteLangDetectionPods: true
  # Ignored namespaces won't show up in odigos-ui
  ignoredNamespaces:
    - odigos-system
    - kube-system
    - local-path-storage
    - istio-system
    - linkerd
  image:
    repository: keyval/odigos-instrumentor

odiglet:
  image:
    repository: keyval/odigos-odiglet

# Pod Security Policy
psp:
  enabled: false

telemetry:
  enabled: true
