annotations:
  artifacthub.io/category: monitoring-logging
  artifacthub.io/changes: '- bump version of VM operator to [0.42.3](https://github.com/VictoriaMetrics/operator/releases/tag/v0.42.3)'
  artifacthub.io/license: Apache-2.0
  artifacthub.io/links: |
    - name: Sources
      url: https://docs.victoriametrics.com/vmgateway.html
    - name: Charts repo
      url: https://victoriametrics.github.io/helm-charts/
    - name: Docs
      url: https://docs.victoriametrics.com
  artifacthub.io/operator: "true"
apiVersion: v2
appVersion: v1.99.0
dependencies:
- condition: victoria-metrics-operator.enabled
  name: victoria-metrics-operator
  repository: https://victoriametrics.github.io/helm-charts
  version: 0.29.*
- condition: kube-state-metrics.enabled
  name: kube-state-metrics
  repository: https://prometheus-community.github.io/helm-charts
  version: 5.16.*
- condition: prometheus-node-exporter.enabled
  name: prometheus-node-exporter
  repository: https://prometheus-community.github.io/helm-charts
  version: 4.27.*
- condition: grafana.enabled
  name: grafana
  repository: https://grafana.github.io/helm-charts
  version: 7.3.*
- condition: crds.enabled
  name: crds
  repository: ""
  version: 0.0.0
description: Kubernetes monitoring on VictoriaMetrics stack. Includes VictoriaMetrics
  Operator, Grafana dashboards, ServiceScrapes and VMRules
home: https://github.com/VictoriaMetrics/helm-charts
icon: https://avatars.githubusercontent.com/u/43720803?s=200&v=4
keywords:
- victoriametrics
- operator
- monitoring
- kubernetes
- observability
- tsdb
- metrics
- metricsql
- timeseries
kubeVersion: '>=1.23.0-0'
name: victoria-metrics-k8s-stack
sources:
- https://github.com/VictoriaMetrics/helm-charts
type: application
version: 0.20.0
