annotations:
  artifacthub.io/links: |
    - name: Projects Homepage
      url: https://gotenberg.dev/
    - name: Projects GitHub
      url: https://github.com/gotenberg/gotenberg
    - name: Chart's GitHub
      url: https://github.com/MaikuMori/helm-charts/tree/master/charts/gotenberg
    - name: Chart's Changelog
      url: https://github.com/MaikuMori/helm-charts/blob/master/charts/gotenberg/CHANGELOG.md
apiVersion: v2
appVersion: 8.12.0
description: A Helm chart for Gotenberg
icon: https://user-images.githubusercontent.com/8983173/130322857-185831e2-f041-46eb-a17f-0a69d066c4e5.png
keywords:
- gotenberg
- pdf
maintainers:
- email: mikskalnins@maikumori.com
  name: MaikuMori
  url: maikumori.com
name: gotenberg
sources:
- https://github.com/gotenberg/gotenberg
- https://github.com/MaikuMori/helm-charts/tree/master/charts/gotenberg
type: application
version: 1.9.0
