apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: odigos-autoscaler
  name: odigos-autoscaler
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: odigos-autoscaler
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: manager
      labels:
        app.kubernetes.io/name: odigos-autoscaler
    spec:
      containers:
      - args:
          - --health-probe-bind-address=:8081
          - --metrics-bind-address=127.0.0.1:8080
          - --leader-elect
          {{ if .Values.image.prefix }}
          - --image-prefix={{ .Values.image.prefix }}
          {{ end }}
        command:
          - /app
        image: "{{ .Values.autoscaler.image.repository }}:{{ .Values.image.tag }}"
        env:
          - name: OTEL_SERVICE_NAME
            value: auto-scaler
          - name: CURRENT_NS
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
        envFrom:
          - configMapRef:
              name: odigos-own-telemetry-otel-config
              optional: true
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        name: manager
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
          requests:
            cpu: 10m
            memory: 64Mi
        securityContext:
          allowPrivilegeEscalation: false
      securityContext:
        runAsNonRoot: true
      serviceAccountName: odigos-autoscaler
      terminationGracePeriodSeconds: 10
      nodeSelector:
        kubernetes.io/os: linux
{{- if .Values.imagePullSecrets }}
      imagePullSecrets:
{{ toYaml .Values.imagePullSecrets | indent 6 }}
{{- end }}
