apiVersion: odigos.io/v1alpha1
kind: Destination
metadata:
  name: odigos.io.dest.qryn-loki
  namespace: monitoring
spec:
  data:
    LOKI_URL: http://{{ .Values.qryn.username }}:{{ .Values.qryn.password }}@qryn.monitoring.svc.cluster.local
  destinationName: qryn-logs
  signals:
  - LOGS
  type: loki
