apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app.kubernetes.io/name: odiglet
  name: odiglet
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: odiglet
  template:
    metadata:
      labels:
        app.kubernetes.io/name: odiglet
    spec:
      containers:
        - name: odiglet
          image: "{{ .Values.odiglet.image.repository }}:{{ .Values.image.tag }}"
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: NODE_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
          envFrom:
            - configMapRef:
                name: odigos-own-telemetry-otel-config
                optional: true
          securityContext:
            privileged: true
            capabilities:
              add:
                - SYS_PTRACE
          volumeMounts:
            - name: run-dir
              mountPath: /run
              mountPropagation: Bidirectional
            - name: var-dir
              mountPath: /var
              mountPropagation: Bidirectional
            - name: odigos
              mountPath: /var/odigos
              mountPropagation: Bidirectional
            - name: kernel-debug
              mountPath: /sys/kernel/debug
      hostNetwork: true
      hostPID: true
      nodeSelector:
        kubernetes.io/os: linux
      serviceAccountName: odiglet
      tolerations:
        - effect: NoSchedule
          key: node.kubernetes.io/os
          operator: Equal
          value: windows
      volumes:
        - name: run-dir
          hostPath:
            path: /run
        - name: var-dir
          hostPath:
            path: /var
        - name: odigos
          hostPath:
            path: /var/odigos
        - name: kernel-debug
          hostPath:
            path: /sys/kernel/debug
{{- if .Values.imagePullSecrets }}
      imagePullSecrets:
{{ toYaml .Values.imagePullSecrets | indent 6 }}
{{- end }}
