{{- if .Values.enabled -}}
{{- $otlp_endpoint := .Values.otlpEndpoint | required ".Values.otlpEndpoint is required!" -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "telemetrygen.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "telemetrygen.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-telemetrygen
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app: {{ .Release.Name }}-telemetrygen
        {{- include "telemetrygen.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      restartPolicy: Always
      containers:
{{- if .Values.traces.enabled }}
        - name: {{ .Chart.Name }}-telemetrygen-traces
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          command:
          - /telemetrygen
          - traces
          - --otlp-insecure
          - >-
            --otlp-endpoint
          - >-
            {{ $otlp_endpoint }}
          - --duration=1h
          - --rate=1
          - >-
            --otlp-attributes
          - >-
            k8s.container.name="{{ .Chart.Name }}-telemetrygen"
          - --service
          - telemetrygen
{{- end }}
{{- if .Values.metrics.enabled }}
        - name: {{ .Chart.Name }}-telemetrygen-metrics
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          command:
          - /telemetrygen
          - metrics
          - --trace-id
          - {{ include "randgen.randHex" 16 }}
          - --span-id
          - {{ include "randgen.randHex" 8 }}
          - --otlp-insecure
          - >-
            --otlp-endpoint
          - >-
            {{ $otlp_endpoint }}
          - --duration=1h
          - --rate=1
          - >-
            --otlp-attributes
          - >-
            k8s.container.name="{{ .Chart.Name }}-telemetrygen"
{{- end }}
{{- if .Values.logs.enabled }}
        - name: {{ .Chart.Name }}-telemetrygen-logs
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          command:
          - /telemetrygen
          - logs
          - --trace-id
          - {{ include "randgen.randHex" 16 }}
          - --span-id
          - {{ include "randgen.randHex" 8 }}
          - --otlp-insecure
          - >-
            --otlp-endpoint
          - >-
            {{ $otlp_endpoint }}
          - --duration=1h
          - --rate=1
          - >-
            --body
          - >-
            {{ .Values.logs.body | indent 12 | trim }}
{{- end }}

      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
