apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    io.metrico.service: qryn
spec:
  replicas: {{ .Values.replicas | default "1" }}
  selector:
    matchLabels:
      io.metrico.service: qryn
  strategy: {}
  template:
    metadata:
      annotations:
        qryn.cmd: qryn.dev
      labels:
        io.metrico.service: qryn}
    spec:
      containers:
      - name: qryn
        image: docker.io/qxip/qryn:bun
        ports:
        - containerPort: 3100
          name: http
          protocol: TCP
        env:
          - name: CLICKHOUSE_AUTH
            value: {{ printf "%s:%s" .Values.clickhouse.username .Values.clickhouse.password | quote }}
          - name: CLICKHOUSE_PORT
            value: {{ .Values.clickhouse.port | default "8123" | quote }}
          - name: CLICKHOUSE_SERVER
            value: {{ .Values.clickhouse.server | default "clickhouse" | quote }}
          - name: CLICKHOUSE_DB
            value: {{ .Values.clickhouse.database | default "qryn" | quote }}
          - name: LOG_LEVEL
            value: {{ .Values.logs.level | default "warn" | quote }}
          - name: QRYN_LOGIN
            value: {{ .Values.qryn.username | default "qryn" | quote }}
          - name: QRYN_PASSWORD
            value: {{ .Values.qryn.password | default "qryn" | quote }}
        resources: {}
      restartPolicy: Always
      resources:
        requests:
          memory: "64Mi"
          cpu: "250m"
        limits:
          memory: "400Mi"
        

