apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    io.metrico.service: qryn
spec:
  replicas: {{ .Values.replicas | default "1" }}
  selector:
    matchLabels:
      io.metrico.service: qryn
  strategy: {}
  template:
    metadata:
      annotations:
        qryn.cmd: qryn.dev
      labels:
        io.metrico.service: qryn
    spec:
      containers:
      - name: qryn
        image: docker.io/qxip/qryn:bun
        ports:
        - containerPort: 3100
          name: http
          protocol: TCP
        env: []
        resources: {}
      restartPolicy: Always
      resources:
        requests:
          memory: "64Mi"
          cpu: "250m"
        limits:
          memory: "400Mi"
        

