apiVersion: v1
kind: Service
metadata:
  labels:
    io.metrico.service: qryn
  name: qryn
spec:
  ports:
    - name: "3100"
      port: 3100
      targetPort: 3100
  selector:
    io.metrico.service: qryn

