apiVersion: v1
kind: Secret
type: kubernetes.io/basic-auth
metadata:
  name: {{ .Release.Name }}
data:
  username: {{ .Values.secret.username | default (randAlphaNum 10) | b64enc | quote }}
  password: {{ .Values.secret.password | default (randAlphaNum 64) | b64enc | quote }}
  database: {{ .Values.secret.database | default (randAlphaNum 64) | b64enc | quote }}
---
apiVersion: v1
data:
  username: {{ .Values.s3.secret.username | default (randAlphaNum 10) | b64enc | quote }}
  password: {{ .Values.s3.secret.password | default (randAlphaNum 64) | b64enc | quote }}
kind: Secret
metadata:
  name: {{ .Release.Name }}-s3
#type: kubernetes.io/basic-auth


