apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: {{ include "openobserve-collector.fullname" . }}-agent
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "openobserve-collector.labels" . | nindent 4 }}
spec:
  mode: daemonset # "daemonset", "deployment" (default), "statefulset"
  serviceAccount: {{ include "openobserve-collector.serviceAccountName" . }}
  image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
  env:
    - name: K8S_NODE_NAME
      valueFrom:
        fieldRef:
          fieldPath: spec.nodeName
  {{- with .Values.agent.tolerations }}
  tolerations:
    {{- toYaml . | nindent 8 }}
  {{- end }}
  volumes:
    - name: hostfs
      hostPath:
        path: /
    - name: varlog
      hostPath:
        path: /var/log
        type: ''
    - name: varlibdockercontainers
      hostPath:
        path: /var/lib/docker/containers
        type: ''
  volumeMounts:
    - name: hostfs
      mountPath: /hostfs
    - name: varlog
      mountPath: /var/log
    - name: varlibdockercontainers
      readOnly: true
      mountPath: /var/lib/docker/containers
  resources: {{ .Values.gateway.resources | toYaml | nindent 4 }}
  config: |
    receivers: {{ .Values.agent.receivers | toYaml | nindent 6 }}
    connectors: {{ .Values.agent.connectors | toYaml | nindent 6 }}
    processors: {{ .Values.agent.processors | toYaml | nindent 6 }}
    extensions: {{ .Values.agent.extensions | toYaml | nindent 6 }}
    exporters: {{ .Values.exporters | toYaml | nindent 6 }}
    service: {{ .Values.agent.service | toYaml | nindent 6 }}
  
