autoscaler:
  image:
    repository: gothenburg/odigos-autoscaler
    tag: 0.0.1

scheduler:
  image:
    repository: gothenburg/odigos-scheduler
    tag: 0.0.1

ui:
  image:
    repository: keyval/odigos-ui
    tag: v0.1.63


instrumentor:
  deleteLangDetectionPods: true
   # Ignored namespaces won't show up in odigos-ui
  ignoredNamespaces:
    - odigos-system
    - kube-system
    - local-path-storage
    - istio-system
    - linkerd
  image:
    repository: gothenburg/odigos-instrumentor
    tag: 0.0.1

odiglet:
  image:
    repository: gothenburg/odigos-odiglet
    tag: 0.0.1

telemetry:
  enabled: true
