autoscaler:
  image:
    repository: keyval/odigos-autoscaler
    tag: v1.0.12

scheduler:
  image:
    repository: keyval/odigos-scheduler
    tag: v1.0.12

ui:
  image:
    repository: keyval/odigos-ui
    tag: v1.0.12


instrumentor:
  deleteLangDetectionPods: true
   # Ignored namespaces won't show up in odigos-ui
  ignoredNamespaces:
    - odigos-system
    - kube-system
    - local-path-storage
    - istio-system
    - linkerd
  image:
    repository: keyval/odigos-instrumentor
    tag: v1.0.12

odiglet:
  image:
    repository: keyval/odigos-odiglet
    tag: v1.0.12

telemetry:
  enabled: true
