apiVersion: v2
appVersion: v0.6.4
dependencies:
- condition: etcd.enabled
  name: etcd
  repository: https://charts.bitnami.com/bitnami
  version: 8.11.4
- condition: minio.enabled
  name: minio
  repository: https://charts.min.io
  version: 5.0.7
description: Logs, Metrics and Traces, Dashboards, RUM, Error tracking, Session replay
  etc. Elasticsearch API compatibility.
maintainers:
- email: hello@openobserve.ai
  name: OpenObserve
  url: https://openobserve.ai
name: openobserve
type: application
version: 0.6.4
