---
# See API: https://github.com/open-telemetry/opentelemetry-operator/blob/main/docs/api.md#opentelemetrycollector
apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
{{- if .Values.collectorName }}
  name: {{ .Values.collectorName }}
{{- else }}
  name: {{ .Values.preset }}
{{- end }}
  namespace: {{ .Release.Namespace }}

spec:
{{- if eq .Values.preset "router" }}
{{- $baseConfig := include "otel-collector-cr.routerBaseConfig" . | fromYaml -}}
{{- $mergedConfig := mustMergeOverwrite (dict) .Values.spec $baseConfig }}
{{ toYaml $mergedConfig | indent 2 }}
{{- else if eq .Values.preset "debug" }}
{{- $baseConfig := include "otel-collector-cr.debugBaseConfig" . | fromYaml -}}
{{- $mergedConfig := mustMergeOverwrite (dict) .Values.spec $baseConfig -}}
{{ toYaml $mergedConfig | indent 2 }}
{{- else }}
{{ toYaml .Values.spec | indent 2 }}
{{- end }}

