{{- if and .Values.enterprise.enabled .Values.enterprise.dex.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "openobserve.fullname" . }}-dex
  namespace: {{ .Release.Namespace | quote }}
spec:
  ports:
    - port: 5556
      targetPort: 5556
  selector:
    app: dex
{{- end }}
