apiVersion: v2
appVersion: 1.5.6
dependencies:
- condition: prometheus.enabled
  name: prometheus
  repository: https://prometheus-community.github.io/helm-charts
  version: 15.16.*
- condition: node-agent.enabled
  name: node-agent
  repository: https://coroot.github.io/helm-charts
  version: 0.1.94
- condition: clickhouse.enabled
  name: clickhouse
  repository: https://charts.bitnami.com/bitnami
  version: 3.1.*
description: A monitoring and troubleshooting tool for microservice architectures.
name: coroot
type: application
version: 0.15.8
